# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER zudp

# 挂载目录
VOLUME /home/zudp
# 创建目录
RUN mkdir -p /home/zudp
# 指定路径
WORKDIR /home/zudp
# 复制jar文件到路径
COPY ./jar/zudp-modules-file.jar /home/zudp/zudp-modules-file.jar
# 启动文件服务
ENTRYPOINT ["java","-jar","zudp-modules-file.jar"]
