# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER zudp

# 挂载目录
VOLUME /home/zudp
# 创建目录
RUN mkdir -p /home/zudp
# 指定路径
WORKDIR /home/zudp
# 复制jar文件到路径
COPY ./jar/zudp-visual-monitor.jar /home/zudp/zudp-visual-monitor.jar
# 启动系统服务
ENTRYPOINT ["java","-jar","zudp-visual-monitor.jar"]
